export { default as AboutMe } from "./about-me.tsx"
export { default as AboutRotW } from "./about-rotw.tsx"
// export { default as Achievements } from "./achievements.tsx"
// export { default as Blog } from "./blog.tsx"
// export { default as Certifications } from "./certifications.tsx"
export { default as Contact } from "./contact.tsx"
// export { default as Designs } from "./designs.tsx"
export { default as Education } from "./education.tsx"
export { default as Footer } from "./footer.tsx"
export { default as Header } from "./header.tsx"
export { default as Languages } from "./languages.tsx"
export { default as Music } from "./music.tsx"
// export { default as Philantrophy } from "./philanthropy.tsx"
// export { default as Photography } from "./photography.tsx"
export { default as Projects } from "./projects.tsx"
export { default as Resume } from "./resume.tsx"
export { default as Skills } from "./skills.tsx"
export { default as WorkExperience } from "./work-experience.tsx"

