export { default as AboutMe } from "./about-me"
export { default as AboutRotW } from "./about-rotw"
// export { default as Achievements } from "./achievements"
// export { default as Blog } from "./blog"
// export { default as Certifications } from "./certifications"
export { default as Contact } from "./contact"
// export { default as Designs } from "./designs"
export { default as Education } from "./education"
export { default as Footer } from "./footer"
export { default as Header } from "./header"
export { default as Languages } from "./languages"
export { default as Music } from "./music"
// export { default as Philantrophy } from "./philanthropy"
// export { default as Photography } from "./photography"
export { default as Projects } from "./projects"
export { default as Resume } from "./resume"
export { default as Skills } from "./skills"
export { default as WorkExperience } from "./work-experience"

